Repository issue-tracker/issue-tracker-web, pull requests merged in 2022-08, with the labels that each got.

#6 ✨💄 회원가입, OAuth 로그인 UI 컴포넌트와 기능 구현 및 테스트
  .storybook/preview.js
  jest.config.js
  package-lock.json
  package.json
  public/index.html
  public/mockServiceWorker.js
  setupTests.ts
  src/App.tsx
  src/Portal.tsx
  src/api/redirectAuth.ts
  src/api/signUp.ts
  src/api/testApi.ts
  src/components/Atoms/Button/index.tsx
  src/components/Atoms/Input/index.tsx
  src/components/Atoms/LoadingSpinner/index.styles.ts
  src/components/Atoms/LoadingSpinner/index.tsx
  src/components/Atoms/OauthLoginButton/index.styles.ts
  src/components/Atoms/OauthLoginButton/index.tsx
  src/components/Modal/CompleteSignUp/index.styles.ts
  src/components/Modal/CompleteSignUp/index.test.tsx
  src/components/Modal/CompleteSignUp/index.tsx
  src/components/Modal/index.styled.ts
  src/components/Modal/index.tsx
  src/components/Molecules/CommonLoginForm/index.tsx
  src/components/Molecules/OauthLoginForm/index.tsx
  src/components/Molecules/SignUpInput/SignUpInput.stories.tsx
  src/components/Molecules/SignUpInput/index.styles.ts
  src/components/Molecules/SignUpInput/index.tsx
  src/components/Organisms/CommonSignUpForm/CommonSignUpForm.stories.tsx
  src/components/Organisms/CommonSignUpForm/constants.ts
  src/components/Organisms/CommonSignUpForm/index.styles.ts
  src/components/Organisms/CommonSignUpForm/index.test.tsx
  src/components/Organisms/CommonSignUpForm/index.tsx
  src/components/Organisms/OauthSignUpForm/OauthSignUp.stories.tsx
  src/components/Organisms/OauthSignUpForm/index.styles.ts
  src/components/Organisms/OauthSignUpForm/index.test.tsx
  src/components/Organisms/OauthSignUpForm/index.tsx
  src/hooks/useInput.tsx
  src/index.tsx
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/mocks/worker.ts
  src/pages/Home.tsx
  src/pages/Private/Issues.tsx
  src/pages/Public/RedirectAuth.tsx
  src/pages/Public/SignUp-Common.tsx
  src/pages/Public/SignUp-OAuth.tsx
  src/pages/index.tsx
  src/router/index.tsx
  src/stores/signUp.ts
  src/stores/userInfo.ts
  webpack/webpack.common.js
  webpack/webpack.dev.js
Labels: 🎨 UI, ✨ feature, 🙉 test

#8 Feature/7 issues page UI dotori
  package-lock.json
  package.json
  src/assets/icons/menu.svg
  src/components/Atoms/CheckBox/CheckBox.stories.tsx
  src/components/Atoms/CheckBox/index.styles.ts
  src/components/Atoms/CheckBox/index.tsx
  src/components/Atoms/Icon/Icon.stories.tsx
  src/components/Atoms/Icon/svgs.tsx
  src/components/Atoms/Label/Label.stories.tsx
  src/components/Atoms/Label/index.styles.ts
  src/components/Atoms/Label/index.tsx
  src/components/Atoms/UserImage/UserImage.stories.tsx
  src/components/Atoms/UserImage/index.styles.ts
  src/components/Atoms/UserImage/index.tsx
  src/components/Molecules/IssueItem/IssueItem.stories.tsx
  src/components/Molecules/IssueItem/index.styles.ts
  src/components/Molecules/IssueItem/index.tsx
  src/components/Molecules/NavLink/NavLink.stories.tsx
  src/components/Molecules/NavLink/index.styles.ts
  src/components/Molecules/NavLink/index.tsx
  src/components/Organisms/Header/Header.stories.tsx
  src/components/Organisms/Header/index.styles.ts
  src/components/Organisms/Header/index.tsx
  src/components/Organisms/IssueTable/IssueList.stories.tsx
  src/components/Organisms/IssueTable/index.styles.ts
  src/components/Organisms/IssueTable/index.tsx
  src/hooks/useCheckBox.ts
  src/stores/checkBox.ts
  src/styles/theme.ts
  src/utils/calcForTimeToday.ts
Labels: 🎨 UI

#9 💄 Dropdown, FilterBar 컴포넌트 UI 구현
  src/components/Atoms/Icon/svgs.tsx
  src/components/Atoms/Input/index.tsx
  src/components/Molecules/Dropdown/Indicator/index.stories.tsx
  src/components/Molecules/Dropdown/Indicator/index.styles.ts
  src/components/Molecules/Dropdown/Indicator/index.tsx
  src/components/Molecules/Dropdown/Panel/Label/index.stories.tsx
  src/components/Molecules/Dropdown/Panel/Label/index.styles.ts
  src/components/Molecules/Dropdown/Panel/Label/index.tsx
  src/components/Molecules/Dropdown/Panel/index.stories.tsx
  src/components/Molecules/Dropdown/Panel/index.styles.ts
  src/components/Molecules/Dropdown/Panel/index.tsx
  src/components/Molecules/Dropdown/index.stories.tsx
  src/components/Molecules/Dropdown/index.styles.ts
  src/components/Molecules/Dropdown/index.tsx
  src/components/Molecules/Dropdown/mocks.ts
  src/components/Molecules/Dropdown/types.ts
  src/components/Molecules/FilterBar/index.stories.tsx
  src/components/Molecules/FilterBar/index.styles.ts
  src/components/Molecules/FilterBar/index.tsx
  src/components/Molecules/FilterBar/mocks.ts
Labels: 🎨 UI, ✨ feature

#12 ✨ 로그인회원가입 api 추가 적용
  src/api/login_logout.ts
  src/api/redirectAuth.ts
  src/api/signUp.ts
  src/api/testApi.ts
  src/components/Atoms/LoadingSpinner/index.styles.ts
  src/components/Molecules/CommonLoginForm/index.tsx
  src/components/Molecules/IssueItem/index.tsx
  src/components/Molecules/NavLink/index.styles.ts
  src/components/Molecules/NavLink/index.tsx
  src/components/Molecules/SignUpInput/index.tsx
  src/components/Organisms/CommonSignUpForm/index.test.tsx
  src/components/Organisms/CommonSignUpForm/index.tsx
  src/components/Organisms/Header/Header.stories.tsx
  src/components/Organisms/Header/index.tsx
  src/components/Organisms/IssueTable/index.tsx
  src/components/Organisms/OauthSignUpForm/index.tsx
  src/hooks/useInput.ts
  src/hooks/useLogin.ts
  src/hooks/useLogout.ts
  src/mocks/handlers.ts
  src/pages/Private/Issues.tsx
  src/pages/Public/RedirectAuth.tsx
  src/router/PrivateRouter.tsx
  src/router/PublicRouter.tsx
  src/router/index.tsx
  src/stores/auth.ts
  src/stores/loginUserInfo.ts
  src/stores/signUp.ts
  src/stores/userInfo.ts
  src/test/CommonSignUpForm.test.tsx
  src/test/CompleteSignUp.test.tsx
  src/test/Header.test.tsx
  src/test/OauthSignUpForm.test.tsx
  src/utils/debounce.ts
  webpack/webpack.dev.js
Labels: ✨ feature, 🔨 refactor, 🙉 test

#16 Feature/13 label UI
  src/components/Atoms/Input/index.tsx
  src/components/Atoms/Label/Label.stories.tsx
  src/components/Atoms/Label/index.styles.ts
  src/components/Atoms/Label/index.tsx
  src/components/Atoms/Radio/index.stories.tsx
  src/components/Atoms/Radio/index.styled.ts
  src/components/Atoms/Radio/index.tsx
  src/components/Molecules/AddLabelField/index.stories.tsx
  src/components/Molecules/AddLabelField/index.styled.ts
  src/components/Molecules/AddLabelField/index.tsx
  src/components/Molecules/IssueItem/IssueItem.stories.tsx
  src/components/Molecules/IssueItem/index.styles.ts
  src/components/Molecules/IssueItem/index.tsx
  src/components/Molecules/NavLink/index.styles.ts
  src/components/Molecules/NavLink/option.tsx
  src/components/Molecules/Table/TableHeader/index.tsx
  src/components/Molecules/Table/TableItem/index.tsx
  src/components/Molecules/Table/index.stories.tsx
  src/components/Molecules/Table/index.styled.ts
  src/components/Molecules/Table/index.tsx
  src/components/Molecules/Table/mock.ts
  src/components/Organisms/IssueTable/index.styles.ts
  src/components/Organisms/IssueTable/index.tsx
  src/components/Organisms/IssueTable/mocks.ts
  src/pages/Private/LabelList.tsx
  src/pages/index.tsx
  src/router/PrivateRouter.tsx
  src/utils/debounce.ts
Labels: 🎨 UI
