Repository issue-tracker/issue-tracker-web, pull requests merged in 2022-12, with the labels that each got.

#50 🐛 이슈 날짜 관련 수정
  src/components/Organisms/IssueHeader/index.tsx
  src/components/Organisms/IssueTable/IssueItem/index.tsx
  src/pages/Private/IssueDetail/index.tsx
  src/utils/calcForTimeToday.ts
Labels: 🔨 refactor

#52 로그인 후 UI 흐름 수정 및 이슈테이블 스켈레톤 UI 적용
  src/App.tsx
  src/components/Organisms/IssueTable/IssueTable.stories.tsx
  src/components/Organisms/IssueTable/TableInfoTabs/index.tsx
  src/components/Organisms/IssueTable/index.tsx
  src/components/Skeleton/IssueTable/SkeletonIssueTable.stories.tsx
  src/components/Skeleton/IssueTable/index.styles.ts
  src/components/Skeleton/IssueTable/index.tsx
  src/components/Skeleton/MilestoneTable/index.styles.ts
  src/pages/Private/Issues/NavInline/index.styled.ts
  src/pages/Private/Issues/NavInline/index.tsx
  src/pages/Private/Issues/index.tsx
  src/pages/Public/RedirectAuth/RedirectAuth.tsx
  src/pages/ServiceLoading.tsx
  src/router/PrivateRouter.tsx
  src/router/PublicRouter.tsx
Labels: 🎨 UI, 🛣 router, 🔨 fix

#53 🤡 레이블, 마일스톤 목핸들러에 이슈테이블 연동
  src/mocks/handlers/label.ts
  src/mocks/handlers/milestone.ts
  src/mocks/tables/issue.ts
Labels: 🤡 mocking
