Repository issue-tracker/issue-tracker-web, pull requests merged in 2022-09, with the labels that each got.

#17 ✨ 마일스톤 페이지 UI 및 기능 구현
  .eslintrc.js
  .storybook/main.js
  .storybook/preview.js
  .storybook/public/mockServiceWorker.js
  package-lock.json
  package.json
  src/api/milestone.ts
  src/components/Atoms/Icon/Icon.stories.tsx
  src/components/Atoms/Icon/index.tsx
  src/components/Atoms/Input/index.styles.ts
  src/components/Atoms/Input/index.tsx
  src/components/Atoms/ProgressBar/ProgressBar.stories.tsx
  src/components/Atoms/ProgressBar/index.styles.ts
  src/components/Atoms/ProgressBar/index.tsx
  src/components/Modal/DeleteMilestone/index.tsx
  src/components/Molecules/Dropdown/Panel/index.styles.ts
  src/components/Molecules/EditMilestone/EditInput/index.styles.ts
  src/components/Molecules/EditMilestone/EditInput/index.tsx
  src/components/Molecules/EditMilestone/EditMilestone.stories.tsx
  src/components/Molecules/EditMilestone/constants.ts
  src/components/Molecules/EditMilestone/index.styles.ts
  src/components/Molecules/EditMilestone/index.tsx
  src/components/Molecules/FilterBar/index.styles.ts
  src/components/Molecules/IssueItem/index.styles.ts
  src/components/Molecules/MilestoneItem/EmptyItem.tsx
  src/components/Molecules/MilestoneItem/MilestoneItem.stories.tsx
  src/components/Molecules/MilestoneItem/constants.ts
  src/components/Molecules/MilestoneItem/index.styles.ts
  src/components/Molecules/MilestoneItem/index.tsx
  src/components/Molecules/NavLink/index.styles.ts
  src/components/Organisms/MilestoneTable/Error/ErrorMilestoneTable.stories.tsx
  src/components/Organisms/MilestoneTable/Error/index.styles.ts
  src/components/Organisms/MilestoneTable/Error/index.tsx
  src/components/Organisms/MilestoneTable/MilestoneTable.stories.tsx
  src/components/Organisms/MilestoneTable/index.tsx
  src/components/Skeleton/MilestoneTable/SkeletonMilestoneTable.stories.tsx
  src/components/Skeleton/MilestoneTable/index.styles.ts
  src/components/Skeleton/MilestoneTable/index.tsx
  src/hooks/useFetchMilestone.ts
  src/mocks/handlers/milestones.ts
  src/mocks/server.ts
  src/mocks/worker.ts
  src/pages/Private/Milestones/MilestonesPage.stories.tsx
  src/pages/Private/Milestones/constants.tsx
  src/pages/Private/Milestones/index.tsx
  src/pages/index.tsx
  src/router/PrivateRouter.tsx
  src/stores/milestone.ts
  src/styles/theme.ts
  src/test/MilestonePage.test.tsx
  src/test/utils.tsx
Labels: 🎨 UI, ✨ feature, 🙉 test

#18 ✨ Label 페이지 기능 구현
  .storybook/main.js
  .storybook/preview.js
  .storybook/public/mockServiceWorker.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/labelList.ts
  src/components/Atoms/ColorCode/index.stories.tsx
  src/components/Atoms/ColorCode/index.styled.ts
  src/components/Atoms/ColorCode/index.tsx
  src/components/Atoms/Icon/index.tsx
  src/components/Atoms/Input/index.tsx
  src/components/Atoms/Label/index.tsx
  src/components/Atoms/Radio/index.tsx
  src/components/Modal/DeleteCheck/index.tsx
  src/components/Molecules/AddLabelField/index.stories.tsx
  src/components/Molecules/AddLabelField/index.styled.ts
  src/components/Molecules/AddLabelField/index.tsx
  src/components/Molecules/IssueItem/index.styles.ts
  src/components/Molecules/IssueItem/index.tsx
  src/components/Molecules/NavLink/option.tsx
  src/components/Molecules/Table/TableItem/index.tsx
  src/components/Molecules/Table/index.stories.tsx
  src/components/Molecules/Table/mock.ts
  src/components/Organisms/Header/Header.stories.tsx
  src/components/Organisms/LabelTable/index.stories.tsx
  src/components/Organisms/LabelTable/index.styled.ts
  src/components/Organisms/LabelTable/index.tsx
  src/components/Skeleton/LabelTable/LabelTableSkeleton.stories.tsx
  src/components/Skeleton/LabelTable/index.styled.ts
  src/components/Skeleton/LabelTable/index.tsx
  src/hooks/useLabelFetch.ts
  src/hooks/useLogin.ts
  src/mocks/handler/auth.ts
  src/mocks/handler/label.ts
  src/mocks/server.ts
  src/mocks/worker.ts
  src/pages/Private/LabelList.tsx
  src/pages/Private/LabelList/LabelList.stories.tsx
  src/pages/Private/LabelList/index.styled.ts
  src/pages/Private/LabelList/index.tsx
  src/router/index.tsx
  src/stores/labelList.ts
  src/test/Header.test.tsx
  src/test/LabelList.test.tsx
  src/test/util.tsx
Labels: ✨ feature, 🔨 refactor

#21 ✨ Label 페이지 기능 구현
  .storybook/main.js
  .storybook/preview.js
  .storybook/public/mockServiceWorker.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/labelList.ts
  src/components/Atoms/ColorCode/index.stories.tsx
  src/components/Atoms/ColorCode/index.styled.ts
  src/components/Atoms/ColorCode/index.tsx
  src/components/Atoms/Icon/index.tsx
  src/components/Atoms/Input/index.tsx
  src/components/Atoms/Label/index.tsx
  src/components/Atoms/Radio/index.tsx
  src/components/Modal/DeleteCheck/index.tsx
  src/components/Molecules/AddLabelField/index.stories.tsx
  src/components/Molecules/AddLabelField/index.styled.ts
  src/components/Molecules/AddLabelField/index.tsx
  src/components/Molecules/IssueItem/index.styles.ts
  src/components/Molecules/IssueItem/index.tsx
  src/components/Molecules/NavLink/option.tsx
  src/components/Molecules/Table/TableItem/index.tsx
  src/components/Molecules/Table/index.stories.tsx
  src/components/Molecules/Table/mock.ts
  src/components/Organisms/Header/Header.stories.tsx
  src/components/Organisms/LabelTable/index.stories.tsx
  src/components/Organisms/LabelTable/index.styled.ts
  src/components/Organisms/LabelTable/index.tsx
  src/components/Skeleton/LabelTable/LabelTableSkeleton.stories.tsx
  src/components/Skeleton/LabelTable/index.styled.ts
  src/components/Skeleton/LabelTable/index.tsx
  src/hooks/useLabelFetch.ts
  src/hooks/useLogin.ts
  src/mocks/handler/auth.ts
  src/mocks/handler/label.ts
  src/mocks/server.ts
  src/mocks/worker.ts
  src/pages/Private/LabelList.tsx
  src/pages/Private/LabelList/LabelList.stories.tsx
  src/pages/Private/LabelList/index.styled.ts
  src/pages/Private/LabelList/index.tsx
  src/router/index.tsx
  src/stores/labelList.ts
  src/test/Header.test.tsx
  src/test/LabelList.test.tsx
  src/test/util.tsx
Labels: ✨ feature, 🔨 refactor

#22 💄✨ label page
  .storybook/main.js
  .storybook/preview.js
  .storybook/public/mockServiceWorker.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/labelList.ts
  src/components/Atoms/ColorCode/index.stories.tsx
  src/components/Atoms/ColorCode/index.styled.ts
  src/components/Atoms/ColorCode/index.tsx
  src/components/Atoms/Icon/index.tsx
  src/components/Atoms/Input/index.tsx
  src/components/Atoms/Label/Label.stories.tsx
  src/components/Atoms/Label/index.styles.ts
  src/components/Atoms/Label/index.tsx
  src/components/Atoms/Radio/index.stories.tsx
  src/components/Atoms/Radio/index.styled.ts
  src/components/Atoms/Radio/index.tsx
  src/components/Modal/DeleteCheck/index.tsx
  src/components/Molecules/AddLabelField/index.stories.tsx
  src/components/Molecules/AddLabelField/index.styled.ts
  src/components/Molecules/AddLabelField/index.tsx
  src/components/Molecules/IssueItem/IssueItem.stories.tsx
  src/components/Molecules/IssueItem/index.styles.ts
  src/components/Molecules/IssueItem/index.tsx
  src/components/Molecules/NavLink/index.styles.ts
  src/components/Molecules/NavLink/option.tsx
  src/components/Molecules/Table/TableHeader/index.tsx
  src/components/Molecules/Table/TableItem/index.tsx
  src/components/Molecules/Table/index.stories.tsx
  src/components/Molecules/Table/index.styled.ts
  src/components/Molecules/Table/index.tsx
  src/components/Molecules/Table/mock.ts
  src/components/Organisms/Header/Header.stories.tsx
  src/components/Organisms/IssueTable/index.styles.ts
  src/components/Organisms/IssueTable/index.tsx
  src/components/Organisms/IssueTable/mocks.ts
  src/components/Organisms/LabelTable/index.stories.tsx
  src/components/Organisms/LabelTable/index.styled.ts
  src/components/Organisms/LabelTable/index.tsx
  src/components/Skeleton/LabelTable/LabelTableSkeleton.stories.tsx
  src/components/Skeleton/LabelTable/index.styled.ts
  src/components/Skeleton/LabelTable/index.tsx
  src/hooks/useLabelFetch.ts
  src/hooks/useLogin.ts
  src/mocks/handler/auth.ts
  src/mocks/handler/label.ts
  src/mocks/server.ts
  src/mocks/worker.ts
  src/pages/Private/LabelList/LabelList.stories.tsx
  src/pages/Private/LabelList/index.styled.ts
  src/pages/Private/LabelList/index.tsx
  src/pages/index.tsx
  src/router/PrivateRouter.tsx
  src/router/index.tsx
  src/stores/labelList.ts
  src/test/Header.test.tsx
  src/test/LabelList.test.tsx
  src/test/util.tsx
  src/utils/debounce.ts
Labels: 🎨 UI, ✨ feature

#27 💄 이슈 생성 페이지 관련 컴포넌트 (TextArea, Sidebar 등) 및 페이지 UI 구현
  src/api/login_logout.ts
  src/components/Atoms/Input/index.styles.ts
  src/components/Atoms/ProgressBar/index.styles.ts
  src/components/Atoms/ProgressBar/index.tsx
  src/components/Atoms/TextArea/TextArea.stories.tsx
  src/components/Atoms/TextArea/index.styles.ts
  src/components/Atoms/TextArea/index.tsx
  src/components/Atoms/UserImage/index.tsx
  src/components/Molecules/Dropdown/Indicator/index.stories.tsx
  src/components/Molecules/Dropdown/Indicator/index.styles.ts
  src/components/Molecules/Dropdown/Indicator/index.tsx
  src/components/Molecules/Dropdown/Panel/index.tsx
  src/components/Molecules/Dropdown/index.stories.tsx
  src/components/Molecules/Dropdown/index.styles.ts
  src/components/Molecules/Dropdown/mocks.ts
  src/components/Molecules/Dropdown/types.ts
  src/components/Molecules/FilterBar/mocks.ts
  src/components/Molecules/MilestoneItem/MilestoneItem.stories.tsx
  src/components/Molecules/MilestoneItem/index.tsx
  src/components/Molecules/SideBar/SideBar.stories.tsx
  src/components/Molecules/SideBar/SideBarItem/index.tsx
  src/components/Molecules/SideBar/index.styles.ts
  src/components/Molecules/SideBar/index.tsx
  src/components/Molecules/SideBar/mock.ts
  src/components/Molecules/SideBar/types.ts
  src/components/Molecules/TextAreaEditer/TextAreaEditer.stories.tsx
  src/components/Molecules/TextAreaEditer/index.styles.ts
  src/components/Molecules/TextAreaEditer/index.tsx
  src/hooks/useFetchSideBarData.ts
  src/mocks/handlers/auth.ts
  src/mocks/handlers/milestones.ts
  src/pages/Private/NewIssue/NewIssue.stories.tsx
  src/pages/Private/NewIssue/index.styles.ts
  src/pages/Private/NewIssue/index.tsx
  src/pages/index.tsx
  src/router/PrivateRouter.tsx
  src/stores/milestone.ts
  src/stores/sidebar.ts
  src/styles/markdown.ts
  webpack/webpack.dev.js
Labels: 🎨 UI

#32 ✨ 이슈 생성 페이지 기능 구현
  jest.config.js
  package-lock.json
  package.json
  src/api/issue/index.ts
  src/api/issue/types.ts
  src/api/issue/useFetchIssue.ts
  src/api/useFetchSideBarData.ts
  src/components/Atoms/Button/options.tsx
  src/components/Atoms/ProgressBar/index.tsx
  src/components/Atoms/TextArea/TextArea.stories.tsx
  src/components/Atoms/TextArea/index.tsx
  src/components/Modal/CancelNewIssue/index.tsx
  src/components/Modal/CompleteSignUp/index.styles.ts
  src/components/Modal/CompleteSignUp/index.tsx
  src/components/Modal/DeleteCheck/index.tsx
  src/components/Modal/DeleteMilestone/index.tsx
  src/components/Modal/index.styled.ts
  src/components/Molecules/Dropdown/Panel/List/index.tsx
  src/components/Molecules/Dropdown/types.ts
  src/components/Molecules/SideBar/SideBar.stories.tsx
  src/components/Molecules/SideBar/SideBarItem/index.tsx
  src/components/Molecules/SideBar/index.tsx
  src/components/Molecules/SideBar/mock.ts
  src/components/Molecules/SideBar/types.ts
  src/components/Molecules/SideBar/utils.ts
  src/components/Molecules/TextAreaEditer/TextAreaEditer.stories.tsx
  src/components/Molecules/TextAreaEditer/constants.ts
  src/components/Molecules/TextAreaEditer/index.tsx
  src/components/Organisms/IssueTable/IssueItem/index.tsx
  src/mocks/handlers/auth.ts
  src/mocks/handlers/issue.ts
  src/mocks/handlers/label.ts
  src/mocks/handlers/milestone.ts
  src/mocks/tables/issue.ts
  src/mocks/tables/newIssueHelper.ts
  src/pages/Private/Issues.tsx
  src/pages/Private/NewIssue/NewIssue.stories.tsx
  src/pages/Private/NewIssue/index.tsx
  src/stores/newIssue.ts
  src/test/MilestonePage.test.tsx
  src/test/NewIssuePage.test.tsx
Labels: 🎨 UI, ✨ feature, 🔨 refactor, 🙉 test

#35 ✅ 테스트 코드 오류 수정
  src/components/Modal/DeleteCheck/index.tsx
  src/mocks/tables/issue.ts
  src/pages/Private/IssueDetail/index.tsx
  src/test/CommonSignUpForm.test.tsx
  src/test/Header.test.tsx
  src/test/IssueDetailPage.test.tsx
  src/test/LabelPage.test.tsx
  src/test/MilestonePage.test.tsx
Labels: 🐞 bug, 🙉 test

#38 ✨ 이슈 필터 기능 구현
  src/App.tsx
  src/api/issue/index.ts
  src/api/issue/types.ts
  src/api/issue/useFetchIssue.ts
  src/api/sign/index.ts
  src/components/Atoms/CheckBox/index.tsx
  src/components/Atoms/Input/index.tsx
  src/components/Atoms/Logo/index.tsx
  src/components/Atoms/TextArea/index.tsx
  src/components/Molecules/CommonLoginForm/index.tsx
  src/components/Molecules/Dropdown/Panel/List/index.styles.ts
  src/components/Molecules/Dropdown/Panel/List/index.tsx
  src/components/Molecules/Dropdown/index.stories.tsx
  src/components/Molecules/Dropdown/index.tsx
  src/components/Molecules/Dropdown/mock.tsx
  src/components/Molecules/Dropdown/types.ts
  src/components/Molecules/FilterBar/index.styles.ts
  src/components/Molecules/FilterBar/index.tsx
  src/components/Molecules/FilterBar/mocks.ts
  src/components/Molecules/LabelEditForm/index.tsx
  src/components/Molecules/NavLink/index.styles.ts
  src/components/Molecules/NavLink/index.tsx
  src/components/Molecules/NavLink/options.tsx
  src/components/Molecules/SideBar/SideBar.stories.tsx
  src/components/Molecules/SideBar/SideBarItem/index.tsx
  src/components/Molecules/SideBar/index.tsx
  src/components/Molecules/SideBar/types.ts
  src/components/Organisms/Header/Header.stories.tsx
  src/components/Organisms/IssueHeader/HeaderInline/index.tsx
  src/components/Organisms/IssueHeader/index.tsx
  src/components/Organisms/IssueTable/IssueItem/index.tsx
  src/components/Organisms/IssueTable/IssueTable.stories.tsx
  src/components/Organisms/IssueTable/index.styles.ts
  src/components/Organisms/IssueTable/index.tsx
  src/components/Organisms/LabelTable/index.styled.ts
  src/components/Organisms/MilestoneTable/index.tsx
  src/components/Organisms/Pagination/index.stories.tsx
  src/components/Organisms/Pagination/index.styled.ts
  src/components/Organisms/Pagination/index.tsx
  src/hooks/useCheckBox.ts
  src/hooks/useFilter.ts
  src/index.tsx
  src/mocks/handlers/auth.ts
  src/mocks/handlers/issue.ts
  src/mocks/handlers/label.ts
  src/mocks/handlers/milestone.ts
  src/mocks/tables/issue.ts
  src/pages/Private/Issues/index.styled.ts
  src/pages/Private/Issues/index.tsx
  src/pages/Private/Labels/index.tsx
  src/pages/Private/Milestones/index.tsx
  src/pages/Private/NewIssue/index.tsx
  src/stores/checkBox.ts
  src/stores/filter.ts
  src/stores/loginUserInfo.ts
Labels: ✨ feature

#39 ✨ 이슈 디테일 추가 기능 구현
  src/api/imageUpload.tsx
  src/api/issue/index.ts
  src/api/issue/types.ts
  src/api/issue/useFetchIssue.ts
  src/api/useFetchSideBarData.ts
  src/components/Atoms/TextArea/TextArea.stories.tsx
  src/components/Atoms/TextArea/index.tsx
  src/components/Molecules/Comment/index.styled.ts
  src/components/Molecules/Comment/index.tsx
  src/components/Molecules/Dropdown/mock.tsx
  src/components/Molecules/TextAreaEditer/TextAreaEditer.stories.tsx
  src/components/Molecules/TextAreaEditer/index.styles.ts
  src/components/Molecules/TextAreaEditer/index.tsx
  src/components/Organisms/IssueHeader/HeaderInline/index.tsx
  src/mocks/handlers/issue.ts
  src/mocks/handlers/milestone.ts
  src/mocks/tables/issue.ts
  src/mocks/tables/issueHistoryHelper.ts
  src/mocks/tables/newIssueHelper.ts
  src/pages/Private/IssueDetail/Aside/index.tsx
  src/pages/Private/IssueDetail/History/History.stories.tsx
  src/pages/Private/IssueDetail/History/index.styles.ts
  src/pages/Private/IssueDetail/History/index.tsx
  src/pages/Private/IssueDetail/index.stories.tsx
  src/pages/Private/IssueDetail/index.tsx
  src/pages/Private/NewIssue/index.tsx
Labels: 🎨 UI, ✨ feature, 🔨 refactor
