Repository issue-tracker/issue-tracker-web, pull requests merged in 2023-01, with the labels that each got.

#55 ♻️ 검색 순으로 필터바에 렌더링 및 마일스톤 페이지 필터 기능 구현
  src/api/issue/index.ts
  src/api/issue/useFetchIssue.ts
  src/components/Molecules/Dropdown/Panel/List/index.styles.ts
  src/components/Molecules/Dropdown/mock.tsx
  src/components/Molecules/FilterBar/index.tsx
  src/components/Molecules/NavLink/index.tsx
  src/components/Molecules/NavLink/options.tsx
  src/components/Organisms/IssueTable/IssueItem/index.tsx
  src/components/Organisms/IssueTable/TableInfoTabs/index.tsx
  src/components/Organisms/IssueTable/index.tsx
  src/components/Organisms/LabelTable/LabelItem/index.tsx
  src/components/Organisms/MilestoneTable/MilestoneItem/index.tsx
  src/components/Organisms/Pagination/index.tsx
  src/hooks/useFilter.ts
  src/mocks/handlers/issue.ts
  src/pages/Private/Issues/index.tsx
  src/stores/filter.ts
Labels: ✨ feature, 🔨 refactor

#56 ⚡️ 웹폰트 최적화 적용
  public/index.html
  src/App.tsx
  src/assets/fonts/NotoSans-Bold.otf
  src/assets/fonts/NotoSans-Bold.woff
  src/assets/fonts/NotoSans-Bold.woff2
  src/assets/fonts/NotoSans-Regular.otf
  src/assets/fonts/NotoSans-Regular.woff
  src/assets/fonts/NotoSans-Regular.woff2
  src/styles/globalFont.css
  webpack/webpack.common.js
Labels: 🔨 refactor

#59 이슈 관련 페이지와 관련된 반응형 화면 구현
  src/components/Molecules/Comment/index.styled.ts
  src/components/Molecules/Dropdown/Indicator/index.styles.ts
  src/components/Molecules/Dropdown/Indicator/index.tsx
  src/components/Molecules/SideBar/index.styles.ts
  src/components/Molecules/Table/index.styled.ts
  src/components/Organisms/Header/index.styles.ts
  src/components/Organisms/IssueHeader/HeaderInline/index.styled.ts
  src/components/Organisms/IssueHeader/index.styled.ts
  src/components/Organisms/IssueHeader/index.tsx
  src/components/Organisms/IssueTable/IssueItem/index.styles.ts
  src/components/Organisms/IssueTable/index.styles.ts
  src/components/Skeleton/IssueTable/index.styles.ts
  src/pages/Home.tsx
  src/pages/Private/IssueDetail/History/index.styles.ts
  src/pages/Private/IssueDetail/IssueInfo/index.styles.ts
  src/pages/Private/IssueDetail/IssueInfo/index.tsx
  src/pages/Private/IssueDetail/index.styled.ts
  src/pages/Private/IssueDetail/index.tsx
  src/pages/Private/Issues/NavInline/index.styled.ts
  src/pages/Private/NewIssue/index.styles.ts
  src/styles/reset.ts
  src/styles/theme.ts
Labels: 🎨 UI, 🔨 fix

#61 🐛 이슈 디테일 페이지 로딩 속도 개선
  src/components/Molecules/Comment/index.tsx
  src/pages/Private/IssueDetail/index.tsx
Labels: 🐞 bug

#62 📱 로그인 및 일반회원가입 페이지 반응형 화면 구현
  src/assets/logo/LogotypeLarge.svg
  src/components/Molecules/CommonLoginForm/index.tsx
  src/components/Molecules/FilterBar/index.styles.ts
  src/components/Organisms/CommonSignUpForm/index.styles.ts
  src/components/Organisms/ErrorTable/index.styles.ts
  src/components/Organisms/LoginAndRegister/index.styles.ts
  src/pages/Private/Issues/NavInline/index.styled.ts
  src/pages/Public/Login.tsx
  src/pages/Public/SignUp-Common.tsx
Labels: 🎨 UI, 🔨 fix
